version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app-container
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"